title: مستندات API
description: پروژه‌ای برای نمایش API به زبان فارسی
markdown: kramdown
sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
